import { EmployeesType } from "./types";

export const employeesData: EmployeesType[] = [
	{
		id: "32132132123",
		name: "jfhdsjk",
		email: "fhkjsfhsjk",
		department: "jghfjfg",
		positions: ["xfgfd", "shsdk", "dkddahg"],
		salary_per_month: 20000,
	},
	{
		id: "98765432101",
		name: "John Doe",
		email: "john.doe@example.com",
		department: "Finance",
		positions: ["Analyst", "Manager"],
		salary_per_month: 30000,
	},
	{
		id: "12345678902",
		name: "Jane Smith",
		email: "jane.smith@example.com",
		department: "HR",
		positions: ["Recruiter", "HR Specialist"],
		salary_per_month: 28000,
	},
	{
		id: "43215678903",
		name: "Michael Johnson",
		email: "michael.johnson@example.com",
		department: "Engineering",
		positions: ["Developer", "Team Lead"],
		salary_per_month: 35000,
	},
	{
		id: "54321678904",
		name: "Emily Davis",
		email: "emily.davis@example.com",
		department: "Marketing",
		positions: ["SEO Specialist", "Marketing Coordinator"],
		salary_per_month: 27000,
	},
	{
		id: "65432789005",
		name: "William Brown",
		email: "william.brown@example.com",
		department: "Sales",
		positions: ["Sales Executive", "Account Manager"],
		salary_per_month: 32000,
	},
	{
		id: "76543890106",
		name: "Olivia White",
		email: "olivia.white@example.com",
		department: "Customer Support",
		positions: ["Support Representative", "Team Lead"],
		salary_per_month: 26000,
	},
	{
		id: "87654901207",
		name: "Sophia Green",
		email: "sophia.green@example.com",
		department: "IT",
		positions: ["System Administrator", "Network Engineer"],
		salary_per_month: 33000,
	},
	{
		id: "98765012308",
		name: "James Clark",
		email: "james.clark@example.com",
		department: "Legal",
		positions: ["Legal Advisor", "Compliance Officer"],
		salary_per_month: 40000,
	},
	{
		id: "09876123409",
		name: "Isabella Lewis",
		email: "isabella.lewis@example.com",
		department: "HR",
		positions: ["HR Manager", "Recruitment Officer"],
		salary_per_month: 29000,
	},
	{
		id: "10987234510",
		name: "Liam Walker",
		email: "liam.walker@example.com",
		department: "Finance",
		positions: ["Financial Analyst", "Accountant"],
		salary_per_month: 34000,
	},
	{
		id: "21098345611",
		name: "Mia Hall",
		email: "mia.hall@example.com",
		department: "Sales",
		positions: ["Sales Executive", "Account Executive"],
		salary_per_month: 31000,
	},
	{
		id: "32109456712",
		name: "Ethan Allen",
		email: "ethan.allen@example.com",
		department: "Engineering",
		positions: ["Frontend Developer", "UI Designer"],
		salary_per_month: 37000,
	},
	{
		id: "43210567813",
		name: "Ava King",
		email: "ava.king@example.com",
		department: "Marketing",
		positions: ["Content Creator", "Social Media Manager"],
		salary_per_month: 25000,
	},
	{
		id: "54321678914",
		name: "Charlotte Young",
		email: "charlotte.young@example.com",
		department: "Customer Support",
		positions: ["Customer Support Agent", "Team Leader"],
		salary_per_month: 27000,
	},
	{
		id: "65432789015",
		name: "Benjamin Wright",
		email: "benjamin.wright@example.com",
		department: "IT",
		positions: ["IT Specialist", "DevOps Engineer"],
		salary_per_month: 32000,
	},
	{
		id: "76543890116",
		name: "Amelia Scott",
		email: "amelia.scott@example.com",
		department: "Legal",
		positions: ["Legal Consultant", "Compliance Manager"],
		salary_per_month: 38000,
	},
	{
		id: "87654901217",
		name: "Lucas Harris",
		email: "lucas.harris@example.com",
		department: "Engineering",
		positions: ["Backend Developer", "Database Administrator"],
		salary_per_month: 36000,
	},
	{
		id: "98765012318",
		name: "Harper Adams",
		email: "harper.adams@example.com",
		department: "Marketing",
		positions: ["Brand Strategist", "Digital Marketing Specialist"],
		salary_per_month: 29000,
	},
	{
		id: "09876123419",
		name: "Henry Baker",
		email: "henry.baker@example.com",
		department: "Finance",
		positions: ["Financial Planner", "Accountant"],
		salary_per_month: 31000,
	},
	{
		id: "10987234520",
		name: "Ella Martinez",
		email: "ella.martinez@example.com",
		department: "Sales",
		positions: ["Sales Representative", "Sales Coordinator"],
		salary_per_month: 30000,
	},
	{
		id: "21098345621",
		name: "Jack Turner",
		email: "jack.turner@example.com",
		department: "Customer Support",
		positions: ["Support Specialist", "Customer Success Manager"],
		salary_per_month: 28000,
	},
	{
		id: "32109456722",
		name: "Grace Rivera",
		email: "grace.rivera@example.com",
		department: "HR",
		positions: ["HR Assistant", "Recruitment Officer"],
		salary_per_month: 26000,
	},
	{
		id: "43210567823",
		name: "Daniel Cox",
		email: "daniel.cox@example.com",
		department: "IT",
		positions: ["System Engineer", "Security Specialist"],
		salary_per_month: 35000,
	},
	{
		id: "54321678924",
		name: "Chloe Howard",
		email: "chloe.howard@example.com",
		department: "Legal",
		positions: ["Legal Assistant", "Corporate Counsel"],
		salary_per_month: 37000,
	},
	{
		id: "65432789025",
		name: "Alexander Lee",
		email: "alexander.lee@example.com",
		department: "Engineering",
		positions: ["Software Engineer", "Project Lead"],
		salary_per_month: 40000,
	},
	{
		id: "76543890126",
		name: "Zoe Perez",
		email: "zoe.perez@example.com",
		department: "Marketing",
		positions: ["Copywriter", "SEO Specialist"],
		salary_per_month: 27000,
	},
	{
		id: "87654901227",
		name: "Sebastian Carter",
		email: "sebastian.carter@example.com",
		department: "Sales",
		positions: ["Sales Manager", "Key Account Manager"],
		salary_per_month: 32000,
	},
	{
		id: "98765012328",
		name: "Lily Evans",
		email: "lily.evans@example.com",
		department: "HR",
		positions: ["HR Coordinator", "People Operations Manager"],
		salary_per_month: 29000,
	},
	{
		id: "09876123429",
		name: "Matthew Torres",
		email: "matthew.torres@example.com",
		department: "Finance",
		positions: ["Auditor", "Tax Specialist"],
		salary_per_month: 36000,
	},
	{
		id: "10987234530",
		name: "Aiden Foster",
		email: "aiden.foster@example.com",
		department: "Engineering",
		positions: ["QA Engineer", "Automation Tester"],
		salary_per_month: 32000,
	},
	{
		id: "21098345631",
		name: "Victoria Diaz",
		email: "victoria.diaz@example.com",
		department: "Customer Support",
		positions: ["Support Agent", "Customer Success Lead"],
		salary_per_month: 27000,
	},
	{
		id: "32109456732",
		name: "David Morris",
		email: "david.morris@example.com",
		department: "IT",
		positions: ["System Administrator", "Cloud Engineer"],
		salary_per_month: 35000,
	},
	{
		id: "43210567833",
		name: "Madison Rogers",
		email: "madison.rogers@example.com",
		department: "Legal",
		positions: ["Contract Specialist", "Legal Advisor"],
		salary_per_month: 39000,
	},
	{
		id: "54321678934",
		name: "Owen Murphy",
		email: "owen.murphy@example.com",
		department: "HR",
		positions: ["HR Generalist", "Recruitment Specialist"],
		salary_per_month: 30000,
	},
	{
		id: "65432789035",
		name: "Evelyn Watson",
		email: "evelyn.watson@example.com",
		department: "Marketing",
		positions: ["Brand Manager", "Content Strategist"],
		salary_per_month: 28000,
	},
	{
		id: "76543890136",
		name: "Samuel Brooks",
		email: "samuel.brooks@example.com",
		department: "Finance",
		positions: ["Financial Analyst", "Risk Manager"],
		salary_per_month: 34000,
	},
	{
		id: "87654901237",
		name: "Layla Gray",
		email: "layla.gray@example.com",
		department: "Sales",
		positions: ["Business Development Manager", "Account Executive"],
		salary_per_month: 31000,
	},
	{
		id: "98765012338",
		name: "Daniel Cooper",
		email: "daniel.cooper@example.com",
		department: "Engineering",
		positions: ["Full-Stack Developer", "Technical Lead"],
		salary_per_month: 37000,
	},
	{
		id: "09876123439",
		name: "Avery Bailey",
		email: "avery.bailey@example.com",
		department: "Customer Support",
		positions: ["Customer Support Manager", "Technical Support Specialist"],
		salary_per_month: 28000,
	},
	{
		id: "10987234540",
		name: "Elijah Thompson",
		email: "elijah.thompson@example.com",
		department: "IT",
		positions: ["DevOps Engineer", "Infrastructure Manager"],
		salary_per_month: 39000,
	},
	{
		id: "21098345641",
		name: "Scarlett Edwards",
		email: "scarlett.edwards@example.com",
		department: "Legal",
		positions: ["Corporate Lawyer", "Compliance Officer"],
		salary_per_month: 41000,
	},
	{
		id: "32109456742",
		name: "Lucas Bell",
		email: "lucas.bell@example.com",
		department: "HR",
		positions: ["People Partner", "HR Manager"],
		salary_per_month: 33000,
	},
];
